name = input("enter your name:")
branch = input("tell me your branch:")
gender =input("what is your gender:")
collegename = input("what is your college name")
age = input("what is your age:")
print("name:",name)
print("branch:",branch)
print("gender:",gender)
print("collegename:",collegename)
print("age:",age)
